apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-zpbk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-zpbk
    app.kubernetes.io/part-of: e2e-dotnet
  name: devfile-sample-dotnet60-basic-zpbk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-zpbk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-zpbk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jlzj-tenant/e2e-dotnet/devfile-sample-dotnet60-basic-zpbk@sha256:6cd23404f2f8868f8bbd2fc21e4abb43107290d38fdbb27f28bdee0b93252a2d
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
